server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://otel-collector:4319/v1/logs
    backoff_config:
      min_period: 1s
      max_period: 5s
    timeout: 10s

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: container
      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: compose_service
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: message
            service: compose_service
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          level:
          service:
          container:
          stream:
    # pipeline_stages:
    #   - json:
    #       expressions:
    #         Properties: Properties
    #   - json:
    #       source: Properties
    #       expressions:
    #         Path: Path
    #         RequestPath: RequestPath
    #   - match:
    #       selector: '{compose_service="library-api"}'
    #       stages:
    #         - drop:
    #             expression: '.Path == "/metrics" or .Path == "/swagger" or .RequestPath == "/metrics" or .RequestPath == "/swagger"'
    #   - match:
    #       selector: '{compose_service="library-api"}'
    #       stages:
    #         - drop:
    #             expression: '"/metrics" in .log' 
    #   - drop:
    #       expression: '"/metrics" in .log'
    #   - drop:
    #       expression: '"/swagger" in .log'